name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Use a valid R version

      - name: Install BiocManager
        run: |
          R -e 'install.packages("BiocManager", repos="https://cran.rstudio.com")'

      - name: Install Bioconductor packages
        run: |
          R -e 'BiocManager::install(c("S4Vectors", "Spectra"))'

      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_cran("rcmdcheck")'
          # Add any other dependencies here
          R -e 'remotes::install_cran("dplyr")' # Example additional dependency
          R -e 'remotes::install_github("yourusername/yourpackagedependency")'

      - name: Check
        run: R -e 'rcmdcheck::rcmdcheck()'
